"""v1.1_pilot_baseline_alignment

Revision ID: 8b3b5867d2ac
Revises: 620be691e3ba
Create Date: 2026-02-11 10:39:47.412005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '8b3b5867d2ac'
down_revision = '620be691e3ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_url', sa.String(length=500), nullable=False),
    sa.Column('merchant_email', sa.String(length=255), nullable=True),
    sa.Column('generated_email', sa.Text(), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_via', sa.String(length=50), nullable=True),
    sa.Column('response_received_at', sa.DateTime(), nullable=True),
    sa.Column('response_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NO_RESPONSE', name='outreachstatus'), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_logs_created_at'), 'outreach_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_logs_merchant_name'), 'outreach_logs', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_outreach_logs_response_status'), 'outreach_logs', ['response_status'], unique=False)
    # Corrected generated enum check if needed, but Enum name is provided.
    
    op.create_table('form_field_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('field_label', sa.Text(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('successful_value', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('form_context', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('human_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('field_label', sa.Text(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Text(), nullable=True),
    sa.Column('prediction_confidence', sa.Float(), nullable=True),
    sa.Column('prediction_source', sa.String(length=50), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('CORRECT', 'WRONG', 'PARTIAL', name='feedbackverdict'), nullable=False),
    sa.Column('corrected_by', sa.UUID(), nullable=False),
    sa.Column('correction_notes', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('llm_usage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('operator_action_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('RESUME_TASK', 'CANCEL_TASK', 'MANUAL_OVERRIDE', 'FEEDBACK_SUBMITTED', 'KILLSWITCH_ENABLED', 'KILLSWITCH_DISABLED', 'QUOTA_ADJUSTED', name='operatoractiontype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('tenant_runtime_flags',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ai_disabled', sa.Boolean(), nullable=False),
    sa.Column('disable_reason', sa.Text(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_by', sa.UUID(), nullable=True),
    sa.Column('max_tasks_per_program', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disabled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )

    # Standardize column types and indexes
    op.add_column('applications', sa.Column('agent_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_applications_agent_status'), 'applications', ['agent_status'], unique=False)
    
    op.add_column('response_pool', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('response_pool', sa.Column('trust_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('response_pool', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key(None, 'response_pool', 'tenants', ['tenant_id'], ['id'])
    
    # Update Embedding column for pgvector consistency
    with op.batch_alter_table('response_pool') as batch_op:
        batch_op.alter_column('embedding',
                   existing_type=sa.JSON(),
                   type_=pgvector.sqlalchemy.Vector(dim=384),
                   existing_nullable=True,
                   postgresql_using='embedding::vector')

    # Indices for new tables
    op.create_index(op.f('ix_llm_usage_log_created_at'), 'llm_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_operator_action_log_created_at'), 'operator_action_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenant_runtime_flags_ai_disabled'), 'tenant_runtime_flags', ['ai_disabled'], unique=False)

def downgrade() -> None:
    op.drop_table('tenant_runtime_flags')
    op.drop_table('operator_action_log')
    op.drop_table('llm_usage_log')
    op.drop_table('human_feedback')
    op.drop_table('form_field_embeddings')
    op.drop_table('outreach_logs')
    op.drop_column('response_pool', 'is_verified')
    op.drop_column('response_pool', 'trust_score')
    op.drop_column('response_pool', 'tenant_id')
    op.drop_column('applications', 'agent_status')
